-- ============================================================
-- meeting-reminder — ALREADY ENABLED on project bqyisdgwtgxxomukozko
-- ============================================================
-- For the record. The edge function `meeting-reminder` is deployed and a
-- pg_cron job runs it every 5 minutes; when a couple's next_meeting time
-- arrives both partners get a "💕 Вы скоро увидитесь!" push (once per
-- meeting, gated by couple_settings.meeting_notified_at).
--
-- Extensions enabled: pg_cron, pg_net.
-- Column added:        couple_settings.meeting_notified_at TIMESTAMPTZ
--
-- The schedule that was applied (anon key is public, only reaches the
-- idempotent function):
--
-- select cron.schedule('meeting-reminder', '*/5 * * * *', $$
--   select net.http_post(
--     url := 'https://bqyisdgwtgxxomukozko.supabase.co/functions/v1/meeting-reminder',
--     headers := jsonb_build_object('Content-Type','application/json',
--       'apikey','<ANON_KEY>','Authorization','Bearer <ANON_KEY>')
--   );
-- $$);
--
-- Inspect:    select * from cron.job where jobname = 'meeting-reminder';
-- Remove:     select cron.unschedule('meeting-reminder');
